import logger from "../utils/logger.js";


export class BaseGenerator {
    constructor(metadata, outputDir) {
        this.metadata = metadata;
        this.outputDir = outputDir;
        this.logger = logger;


    }
    sanitizeName(name) {
        return name.replace(/[^a-zA-Z0-9_]/g, '_');
    }


    generateDDL() {
        /**
         * we are going to generate the DDL for the database..!
         * As the ddl will be a combination of the header,drops,create table,foreign keys,indexes..!
         * IS the template for the base-generator..!
         * we will use this base-to use in child classes..!
         */
        const parts = [];//empty array..!
        parts.push(this.generateHeader());
        parts.push('');
        parts.push(this.generateDrops());
        parts.push('');

        //generation of the tables..!
        for (const table of this.metadata.tables.values()) {
            parts.push(this.generateCreateTable(table));
            parts.push('');

        }
        //generation of the foreign keys..!
        for (const table of this.metadata.tables.values()) {
            const fks = this.generateForeignKeys(table);
            if (fks.length > 0) {
                parts.push(fks);
                parts.push('');
            }
        }
        //generation of indexs..!   
        for (const table of this.metadata.tables.values()) {
            const indexs = this.generateIndexes(table);
            if (indexs && indexs.length > 0) {
                // If indexes is an array, join with newlines
                if (Array.isArray(indexs)) {
                    parts.push(indexs.join('\n'));
                } else {
                    parts.push(indexs);
                }
                parts.push('');
            }
        }
        //return the whole parts and join with \n(new line)..!A
        return parts.join('\n');
    }
    generateHeader() {
        return `-- Generated by Phase-2 MySQL Physical Model Generator (Node.js)
-- Database: MySQL
-- Tables: ${this.metadata.tableCount} | Columns: ${this.metadata.totalColumns}
-- DO NOT EDIT MANUALLY`;
    }


    generateDrops() {
        const drops = ['-- Drop existing tables (reverse order for FK dependencies)'];
        /**
         * as this all in obejct format so take the array from it and reverse it..(Keys..!)
         */
        const tableNames = Array.from(this.metadata.tables.keys()).reverse();

        for (const tableName of tableNames) {
            //if the table is already exist there..!
            drops.push(`DROP TABLE IF EXISTS ${this.sanitizeName(tableName)};`);
        }

        return drops.join('\n');
    }


    /**
     * Used in the child classes..!
     */
    // Abstract methods - must be implemented by subclasses
    generateCreateTable(table) {
        throw new Error('generateCreateTable must be implemented');
    }

    generateForeignKeys(table) {
        throw new Error('generateForeignKeys must be implemented');
    }

    generateIndexes(table) {
        throw new Error('generateIndexes must be implemented');
    }
}
